### ISSUE TITLE
History displays messed up times

### ISSUE THREAD

**Issue by cryodream** [jbrodriguez/unbalance#10]
Sometimes history displays times, with un-rounded seconds, which messes up the UI.
Also, this second one - the time displayed as NaN - happened to me just now for the very first time.

![2018-09-15_08-32-02__chrome](https://user-images.githubusercontent.com/844036/45586300-89363f00-b8c2-11e8-969c-834c8e6d6a6d.png)

**Comment by cryodream** [comment]
Nope, proper files move.
I have never actually done a dry run. What is a point of dry run, exactly?

**Comment by jbrodriguez** [comment]
dry-run has more meaning in scatter operations, since you get a picture of where the separate folders/files end up, i guess.
