### ISSUE TITLE
Feature Request: "Balance" Job

### ISSUE THREAD

**Issue by maxwai** [jbrodriguez/unbalance#106]
It would be nice to have the option to balance the data between disks. This would be very useful when adding a new disk.

Right now one needs to calculate themselves how much data from each existing disk needs to be moved to the new disks to have a balanced usage across disks.

Here is an idea how this could look like:

- User chooses the source and target disks (from where to where should be moved)
- Optionally the user chooses which shares/folders should be taken into account when trying to move (Or the inverse, so the user excludes some shares/folders)
- User chooses how the data that is moved is chosen, this can be one of:
  - sequentially: first files found when traversing the filetree of a disk are choosen
  - random: files are chosen at random
  - depth random: folders at a specific folder depth are chosen at random
- User chooses the threshold where the disks are considered balanced (because files are not all the same size it is not always possible to perfectly balance the data), here the User can enter a byte amount or a percentage.
- Plugin goes through the file tree and tries to find a configuration where the threshold is met. If a byte threshold was given, it tries to have the same amount in bytes on every disk +/- the threshold. If a percentage was given, it tries to have the same percentage of used spaces on every disks +/ the threshold.

Unfortunately I'm not good enough in TS or GO to write it myself but I would be willing to create and write down the logic of what exactly needs to be done to do this (for example with pseudo-code or something similar)

Would be nice to know if interest is there to add this to the plugin.

**Comment by jbrodriguez** [comment]
hi, this looks very much like the "algorithm plugins" ive discussed in the forums https://forums.unraid.net/topic/43651-plugin-unbalanced/?do=findComment&comment=1454260

don't have bandwidth to explore though

**Comment by maxwai** [comment]
True this could be solved with the "algorithm plugin".
