### ISSUE TITLE
Plan step hangs with no output (gather and scatter)

### ISSUE THREAD

**Issue by calonmerc** [jbrodriguez/unbalance#107]
I've tried to use the gather command to begin emptying some older and smaller disks for removal, but it never showed any output in the plan step. Days later, it still showed nothing and I refreshed the page, causing it to return to step 1. Trying a gather operation instead, it appears to be hanging as well. 
![image](https://github.com/user-attachments/assets/affd93c2-9e92-4c17-ab9c-3e4532052563)

Logs from the attempted scatter operation:
[scatter.log](https://github.com/user-attachments/files/17544594/scatter.log)

Logs from the attempted gather operation:
[gather.log](https://github.com/user-attachments/files/17544592/gather.log)

**Comment by calonmerc** [comment]
The plugin is currently in the state shown in the screenshot, no output and cannot cancel or click anything.

**Comment by calonmerc** [comment]
I left that tab open when I left for lunch, came back and it had output, but still not finished. Maybe it's just going to take ages upon ages.

The log has additional data in it, as well.

There are no errors in the Chrome dev console.

The first time I tried, I left it for days with no progress. I'll just let this go and see if it ever progresses.

**Comment by jbrodriguez** [comment]
strange, you can monitor on the terminal`ps aux | grep unbalanced`, to check if it's doing something

the only thing i can think of is that the disks have errors or that the drive is being emulated by parity

**Comment by calonmerc** [comment]
I don't know if it's just timing out or what, but I've now let it go twice for about 2 days each, coming back to it, it's back to step 1?

**Comment by jbrodriguez** [comment]
not sure how to help with this one, open a new issue if this somehow persists
