### ISSUE TITLE
Feature request: select all checkbox

### ISSUE THREAD

**Issue by SvbZ3r0** [jbrodriguez/unbalance#108]
![image](https://github.com/user-attachments/assets/e1d29e8f-dace-45ba-9098-c04c3d5ae062)
Can we have a select all checkbox here for files/folders? And also possibly for target disks? (This would be useful when you want to empty a drive by moving to all other drives). Just a small nice QoL feature.

**Comment by jbrodriguez** [comment]
absolutely, i didnt migrate it from the prev version and miss it too 😀

not so sure for files/folders, but certainly for targets

**Comment by SvbZ3r0** [comment]
Ohh great! What would the issue be with files/folders?

**Comment by jbrodriguez** [comment]
wrt to files/folders, select all would select all the way down to the last file, meaning potentially an rsync command for each file, which is definitely a no-go

to prevent that it would require some logic on top of the current one, to select/deselect parents/children when a folder is selected, so there's some complexity there as well

**Comment by jbrodriguez** [comment]
restored here https://github.com/jbrodriguez/unbalance/releases/tag/2024.12.22
