### ISSUE TITLE
Split-level?

### ISSUE THREAD

**Issue by sarink** [jbrodriguez/unbalance#11]
Does unbalance respect the split-level of a share at all? I realize that it moves files between _disks_ (not shares) directly, so I suspect not. With that being said, is there a way to avoid fragmentation?

I have my split-level set to 2, which means that entire tv series and entire movie folders will always be stored together on a single disk.

If I try to scatter data from a disk, I assume that unbalance will fragment these folders? If so, to what extent? And how could I put things back together?

Thanks!

**Comment by jbrodriguez** [comment]
Hi,

I missed replying to this issue.

unbalance works at the disk level, so it bypasses any share rule you have set.

Scatter will try to pack all seasons of a show on a single disk, given it has enough space.

Give it try, you don't need to actually run it, but you'll see what I mean.

**Comment by jbrodriguez** [comment]
Closing this one, feel free to add any additional comment.
