### ISSUE TITLE
History page showing error starting version 2024.12.22

### ISSUE THREAD

**Issue by EdenNelson** [jbrodriguez/unbalance#111]
starting with starting version 2024.12.22 History Page shows error:
Unexpected Application Error!
Minified React error #185; visit https://react.dev/errors/185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #185; visit https://react.dev/errors/185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ws (http://...:7090/assets/index-CHJGiR34.js:48:29976)
...
💿 Hey developer 👋

You can provide a way better UX than this when your app throws errors by providing your own ErrorBoundary or errorElement prop on your route.

**Comment by jbrodriguez** [comment]
thanks for the report !
should be fixed in https://github.com/jbrodriguez/unbalance/releases/tag/2024.12.23
