### ISSUE TITLE
404 on F5/Refresh

### ISSUE THREAD

**Issue by rgr4y** [jbrodriguez/unbalance#12]
Out of habit, I'll often refresh the browser window assuming a page is locked or frozen. Unfortunately, this results in a 404 with a JSON message and you have to re-type the URL or close the window. It'd be nice if the 404 page redirected to / if the request isn't through Xmlhttprequest.

Minor annoyance. Thanks for all of your hard work :)

**Comment by jbrodriguez** [comment]
Hi, hadn't seen this issue.

Yes, it has to do with the router library (or more specifically, the way I'm using it).

I'll have this in mind for a future release

**Comment by mplewis** [comment]
I believe this issue can be fixed if you have your Go server answer requests to `/*` and redirect them to `/`. I can take a look and possibly submit a PR for this sometime.

**Comment by jbrodriguez** [comment]
Hi, yes, I think it has something to do with that. If you can take a look, you're very welcome 👍🏼

**Comment by recoiladam** [comment]
This is still an issue for anyone having this problem. I am a Vue developer (never used React) and with Vue Router, you will get this same issue if you do not use history mode. Not sure what the equivalent for React is though.
