### ISSUE TITLE
Settings don't stay set

### ISSUE THREAD

**Issue by flick1999** [jbrodriguez/unbalance#13]
I have to change the minimum free space from 450MB to my preference every time I use it. Possible to adjust it so that if I change it, the new value sticks?

Thank you.

**Comment by jbrodriguez** [comment]
Hi, that's odd.

The settings should stick.

I'll take a look at the code.

**Comment by flick1999** [comment]
Thank you. Let me know if I can assist in any way, say by providing logs or
something.

**Comment by jbrodriguez** [comment]
Hi, this was fixed in https://github.com/jbrodriguez/unbalance/commit/b9678b5cdd72961728b70cfea13743186b8ff7eb, so I'm closing the issue.

Feel free to comment if you find any issue.

Thanks for the report !

**Comment by flick1999** [comment]
Excellent, thank you!

**Comment by flick1999** [comment]
Confirmed as resolved. Thanks again for the fast response!
