### ISSUE TITLE
web UI not opening within unRAID

### ISSUE THREAD

**Issue by ziggyke** [jbrodriguez/unbalance#2]
If you're going to look into the code and perform a fix for issue #1 then it is maybe possible to check why the link to the web UI within the Unbalance plugin settingspage on unRAID opens a blank page?

Instead opening a new tab/page with http://<IP/hostname>:<'port'>?

<img width="1272" alt="schermafbeelding 2016-11-24 om 23 36 52" src="https://cloud.githubusercontent.com/assets/8607242/20610816/9555a7ba-b29f-11e6-94f5-eff0abd175b1.png">

**Comment by jbrodriguez** [comment]
Thanks @ziggyke, yes I addressed the issue in 1.8.1.

There were still some other issues with 1.8.1 though, so I'm publishing a new release.

**Comment by ziggyke** [comment]
Even in version 1.8.2 the open web UI opens a blank page...
It is clickable, but there isn't any address behind the hyperlink.

**Comment by ziggyke** [comment]
nope even with version 1.8.3 the web UI link in the settings page opens a blank tab/window.

**Comment by jbrodriguez** [comment]
mmm ... what does the url show ? 

can you try a force refresh of the settings page (Shift + click refresh button) ?

**Comment by ziggyke** [comment]
there isn't an url shown, because it just opens a new tab/window without an url.
I've already cleared my cache an history, tried another browser but still it is a link without url behind it.

**Comment by jbrodriguez** [comment]
ok, disable/enable the service.

Then, if you hover over the link, it "should" show a link at the bottom of the page (a la status bar).

Does it ?

**Comment by ziggyke** [comment]
yes I already checked that, but didn't address it properly in my previous comment.
But hovering over the link doesn't give ma anything in the status bar like other hyperlinks do.

**Comment by jbrodriguez** [comment]
mm ok ... two things:
Can you inspect the element ? I'm guessing the href="" is blank ?
Can you post the first block of ```<?php ... ?>``` of your /usr/local/emhttp/plugins/unbalance/unbalance.page ?
this is mine
```php
<?php
$sName = "unbalance";
$unbalance_cfg = parse_plugin_cfg("unbalance");
$unbalance_service = isset($unbalance_cfg['SERVICE']) ? $unbalance_cfg['SERVICE'] 	: "disable";
$unbalance_runas = isset($unbalance_cfg['RUNAS']) 		? $unbalance_cfg['RUNAS'] 		: "nobody";
$unbalance_port = (isset($unbalance_cfg['PORT']) && is_numeric($unbalance_cfg['PORT']) && $unbalance_cfg['PORT'] > 0 && $unbalance_cfg['PORT'] < 65535 ) ? $unbalance_cfg['PORT'] : "6237";
$unbalance_ip = (isset($var['IPADDR'])) ? $var['IPADDR'] : $eth0['IPADDR:0'];
$unbalance_running = shell_exec("pidof unbalance | wc -w");
$unbalance_version = shell_exec("cat /usr/local/emhttp/plugins/unbalance/VERSION");
$unbalance_version = ($unbalance_running == 1) ?
	"<a style='color:green;' target='_blank' href='http://".$unbalance_ip.":".$unbalance_port."' title='unBALANCE plugin'><b>Open Web UI ( v$unbalance_version)</b></a>":
	"<b><font style='color:orange;'>unBALANCE v$unbalance_version</font></b>";
?>
```

**Comment by ziggyke** [comment]
inspect element from the webpage href="" is not blank...:
```
<p>
<a style='color:green;' target='_blank' href='http://:6237' title='unBALANCE plugin'>
<b>Open Web UI ( v1.8.3)</b>
</a>
</p>
```

I checked the hover over the text in a different browser and there I can see that the hyperlink is pointing to: ":6237" and this opens not exactly a blank page like I described but he's trying to go to webpage: http://localhost:6237 (browser itself puts the "localhost" in the link when opening the new tab)

for unbalance.page this is my output:
```
<?php
$sName = "unbalance";
$unbalance_cfg = parse_plugin_cfg("unbalance");
$unbalance_service = isset($unbalance_cfg['SERVICE']) ? $unbalance_cfg['SERVICE']       : "disable";
$unbalance_runas = isset($unbalance_cfg['RUNAS'])               ? $unbalance_cfg['RUNAS']               : "nobody";
$unbalance_port = (isset($unbalance_cfg['PORT']) && is_numeric($unbalance_cfg['PORT']) && $unbalance_cfg['PORT'] > 0 && $unbalance_cfg['PORT'] < 65535 ) ? $unbalance_cfg['PORT'] : "6237";
$unbalance_ip = (isset($var['IPADDR'])) ? $var['IPADDR'] : $eth0['IPADDR:0'];
$unbalance_running = shell_exec("pidof unbalance | wc -w");
$unbalance_version = shell_exec("cat /usr/local/emhttp/plugins/unbalance/VERSION");
$unbalance_version = ($unbalance_running == 1) ?
        "<a style='color:green;' target='_blank' href='http://".$unbalance_ip.":".$unbalance_port."' title='unBALANCE plugin'><b>Open Web UI ( v$unbalance_version)</b></a>":
        "<b><font style='color:orange;'>unBALANCE v$unbalance_version</font></b>";
?>
```

Maybe worth mentioning that I've 2 eth ports in my server:
Interface eth 0 -> up and running
Interface eth 1 -> down and disabled
Can it be that your plugin is trying to fetch the IP of my disabled eth interface?

**Comment by jbrodriguez** [comment]
mmm .. so it's still picking up a blank ip ...

ok ... i'm guessing you're running 6.3.x ... 

if you look into your ```/usr/local/emhttp/state/network.ini``` (i think that's the correct location), is there an eth0 section, with an IPADDR:0 key pointing to some ip ?
Is there en eth1 section, with an IPADDR:1 key pointing to some ip ?

**Comment by ziggyke** [comment]
No I'm actually running 6.2.4...

This is my complete network.ini and only mentions eth0:
```
[eth0]
BONDING="no"
BONDNAME="bond0"
BONDNICS="eth0,eth1,eth2,eth3"
BONDING_MODE="1"
BONDING_MIIMON="100"
DHCP_KEEPRESOLV="no"
DNS_SERVER1="195.130.130.4"
DNS_SERVER2="195.130.131.4"
BRIDGING="yes"
BRNAME="br0"
BRNICS="eth0"
BRSTP="no"
BRFD="0"
DESCRIPTION:0=""
USE_DHCP:0="yes"
IPADDR:0="192.168.0.212"
NETMASK:0="255.255.255.0"
GATEWAY="192.168.0.1"
MTU=""
TYPE="access"
```

**Comment by jbrodriguez** [comment]
ok, you're running 6.2.4
In your ```/usr/local/emhttp/state/var.ini``` (don't post it since it contains sensitive info), what does the IPADDR key holds ?

**Comment by ziggyke** [comment]
Yes that's correct.
I see there is sensitive info in it ;)

The part I can share is the following:
```
GATEWAY="192.168.0.1"
HWADDR=""
IPADDR=""
```

So no HWADDR and IPADDR are filled in... Should I create a ticket/issue to unRAID?
Because if I go to the network settings of my unRAID setup the eth0 shows the HWADDR (I presume MAC) and IPADDR...

**Comment by jbrodriguez** [comment]
Hi @ziggyke , I'll make a small adjustment to the plugin template to fix this.

Thanks for walking through the issue with me.

**Comment by ziggyke** [comment]
ok thanks you're welcome.
So I don't need to contact unRAID to notify them on this ini file not correctly announcing the HWADDR and IPADDR?

Thanks for addressing this issue.

**Comment by jbrodriguez** [comment]
No, not really, unRAID has been making some changes to how they manage internally the network settings. 

In 6.3.x, there are no longer GATEWAY, HWADDR, IPADDR in var.ini

That's how it will work going forward.

**Comment by ziggyke** [comment]
ah ok, great to here that you can perform a workaround that will work on both 6.2.4, 6.3.x and going forward.

**Comment by ziggyke** [comment]
I found how to solve the problem.
I edited the following file:
`/usr/local/emhttp/plugins/unbalance/unbalance.page`

This line (row 11):
`$unbalance_ip = (isset($var['IPADDR'])) ? $var['IPADDR'] : $eth0['IPADDR:0'];`
should be replaced with this:
`$unbalance_ip = $eth0['IPADDR:0'];`
and that worked for me!

Don't know if this will work with previous versions of unRAID but on the 6.2.4 this works.

**Comment by jbrodriguez** [comment]
Yes, that works for 6.2.x

The general solution isn't too different from the original line
```$unbalance_ip = (isset($var['IPADDR'])) && $var['IPADDR'] != "" ? $var['IPADDR'] : $eth0['IPADDR:0'];```

It's implemented in unBALANCE v1.8.4

**Comment by ziggyke** [comment]
and confirming that now everything is running smooth for opening the webUI from within the plugin settings page!

Thanks for the great and quick support!
I think it is safe to close this issue.

Maybe you also notify this in the thread on the forum ;-)

**Comment by jbrodriguez** [comment]
Thanks for the confirmation @ziggyke !

Yes, I published the release in the forum, so people should be aware.

Closing this issue now :)
