### ISSUE TITLE
v3.10 Removed Files without actually moving them

### ISSUE THREAD

**Issue by BDaddyG** [jbrodriguez/unbalance#3]
1st time using Unbalance and I ran into an issue.

I followed the steps as listed: 
selected the "From" drive,
selected 1 "To" drive
selected folders to move
clicked the CALCULATE button - reported 330GB of files to move
clicked "move" with "Dry Run" checked - log output look OK
repeated the above steps, only with "Dry Run" unchecked
process finished in 20 seconds

the "To" drive has no files, the the "From" drive is now empty.

The entries from the Log shows:
....
I: 2017/06/30 22:14:07 core.go:802: Command Started: rsync -avPRX --dry-run "Thumbnails/2" "/mnt/disk6/"

I: 2017/06/30 22:14:07 core.go:884: Command Finished

I: 2017/06/30 22:14:07 core.go:890: Current progress: 99.71% done ~ 0s left (47655.92 MB/s)

I: 2017/06/30 22:14:07 core.go:900: Removing: rm -rf "/mnt/disk4/Thumbnails/2"

I: 2017/06/30 22:14:08 core.go:802: Command Started: rsync -avPRX --dry-run "Thumbnails/a" "/mnt/disk6/"

I: 2017/06/30 22:14:08 core.go:884: Command Finished

I: 2017/06/30 22:14:08 core.go:890: Current progress: 99.74% done ~ 0s left (45807.58 MB/s)

I: 2017/06/30 22:14:08 core.go:900: Removing: rm -rf "/mnt/disk4/Thumbnails/a"
...

As you can see the rsync command still has "--dry-run" even though the "Dry Run" box had been unchecked.

Is there a way of seeing the complete log so see what was all removed?

Thanks

**Comment by jbrodriguez** [comment]
Hi @BDaddyG , it's a bit strange.

The logs are at /boot/logs/unbalance...

Yes, it uses the settings from the calculate phase (I need to disable the dry-run checkbox after calculate).

Let me review this.

**Comment by BDaddyG** [comment]
I can share the log file if you think it would help you in any way.

**Comment by jbrodriguez** [comment]
Yes, i sent a reply on the forum.

**Comment by jbrodriguez** [comment]
This was solved in a [3.1.1](https://github.com/jbrodriguez/unbalance/releases/tag/3.1.1)
