### ISSUE TITLE
6.9.0 status:stop

### ISSUE THREAD

**Issue by kdush** [jbrodriguez/unbalance#37]
i can't running it on 6.9.0 
support please~
lucky

**Comment by jbrodriguez** [comment]
Hi, what error are you getting ?

**Comment by kdush** [comment]
> Hi, what error are you getting ?

thinks report
let's me record screen later~

**Comment by pr0ntoActual** [comment]
I try to install on 6.9.0-rc2

plugin: installing: https://raw.githubusercontent.com/jbrodriguez/unraid/master/plugins/unbalance.plg
plugin: downloading https://raw.githubusercontent.com/jbrodriguez/unraid/master/plugins/unbalance.plg
plugin: downloading: https://raw.githubusercontent.com/jbrodriguez/unraid/master/plugins/unbalance.plg ... done
plugin: downloading: "https://github.com/jbrodriguez/unbalance/releases/download/5.6.3/unbalance-5.6.3.tgz" ... failed (Generic error)
plugin: "https://github.com/jbrodriguez/unbalance/releases/download/5.6.3/unbalance-5.6.3.tgz" download failure (Generic error)

Don't know if that helps, slightly older thread, but might as well try
