### ISSUE TITLE
Using unbalance to move appdata dir without changing permission

### ISSUE THREAD

**Issue by OmgImAlexis** [jbrodriguez/unbalance#4]
Is it possible to use unbalance to move an appdata directory off of a disk without it changing the directory or file permissions?

**Comment by jbrodriguez** [comment]
It uses rsync internally which (as per the default flags used) is set to copy files/folders permissions (as well as modification time and other metadata).

Just make sure that the user under which unBALANCE is run (nobody by default), has rights to access/copy the files.

**Comment by OmgImAlexis** [comment]
Yeah I noticed that after I ran it, maybe you should add a warning to which top level directory the permissions error is for. I wanted to move all the files off of my drive as I wanted to shrink my array and I thought I had stuffed something up as it was still showing permission issues after running the safe docker new permissions plugin.

I realised after posting this that the permissions were fine and it was just the appdata directory that had the "issue" since the files in it weren't owned by "nobody".

**Comment by jbrodriguez** [comment]
Closing this one, feel free to add any comment
