### ISSUE TITLE
Unbalance to unassigned disks

### ISSUE THREAD

**Issue by cescm** [jbrodriguez/unbalance#41]
Would be possible to implement unbalance from array to unassigned disks?

**Comment by jbrodriguez** [comment]
If I recall correctly, I took a stab at supporting unassigned disks but found that some core code required quite some refactoring.

And since real world work has limited the time I can dedicate to other projects, I've had no option but leave this in the back log :)

**Comment by jbrodriguez** [comment]
non-trivial amount of time/work to support this, i want to implement it, not sure when though
