### ISSUE TITLE
Custom flags allows 'bad' options 

### ISSUE THREAD

**Issue by techie2000** [jbrodriguez/unbalance#47]
I added the --crtimes flag to the Custom flags option and saved it. It was accepted without warning/error.
When I then try and run a sync, unbalance hangs and the only way to recover is to Enable unBALANCE Server = No, and then again to yes to re-instantiate.

Running from cli  IDs why it fails
```
rsync: This rsync does not support --crtimes (-N)
rsync error: syntax or usage error (code 1) at main.c(1746) [client=3.2.3]
```

The input form needs to validate what is input before committing, or the error when running with a bad option needs to be trapped and the user returned to a recoverable state (preferably with details of the error so they can fix it)

**Comment by jbrodriguez** [comment]
hi, i'll be adding a notice in the rsync flags settings page, indicating that the app doesn't perform validation of the flags manually entered.

as you saw, you need to actually run the command to perform that validation, which is not practical in this context
