### ISSUE TITLE
Redirect logging to syslog

### ISSUE THREAD

**Issue by nshores** [jbrodriguez/unbalance#5]
I'd like to have the option to redirect the output of the log from /boot/logs/unbalance.log to /var/log/syslog. This would allow syslog monitoring and would be a good way to get notifications about when large operations are complete.

**Comment by jbrodriguez** [comment]
Hi, yes I can look into logging to /var/log/syslog.

I do have to say that you can get notifications today, the app uses standard notifications api, at various stages of the operations (calculating, starting a transfer, finishing a transfer).

You set them up in unRAID first, then set it up in the app (Settings > Notifications).

Unless you're doing some syslog processing on your own ?

**Comment by nshores** [comment]
Oh, I wasn't aware you already had those API calls setup to tie into the Unraid Notifications. I can actually just use that for the same purpose. I am doing external syslog monitoring, but I won't need that now.
