### ISSUE TITLE
[Feature Request] - Support for 6.9's multi-cache pool feature

### ISSUE THREAD

**Issue by teambvd** [jbrodriguez/unbalance#50]
6.9 introduced multiple cache pools, though unBalance is currently hardcoded for 'Single Cache + Single Array' currently - it'd be great to have it support multiple cache pools, and depending on how it's implemented, could also help lay the groundwork for the upcoming multi-array feature (planned for 6.11 was the last I heard).

**Comment by jbrodriguez** [comment]
hi thanks for opening the issue.

i can look into supporting multiple cache pools, but since i don't use it, i need data in order to figure out how to implement it.

this post lays out what i need: https://forums.unraid.net/topic/43651-plug-in-unbalance/?do=findComment&comment=1017037

**Comment by flallnatural** [comment]
Was this feature added? I was reading on the unRAID forums that this was discussed some time last year. What kind of information do you need?

**Comment by teambvd** [comment]
Wasnt added; he wants this:
https://github.com/jbrodriguez/controlr-support

**Comment by djlongy** [comment]
Any chance of implementing multiple cache pools?

**Comment by jbrodriguez** [comment]
i could eventually look into it, but need some info https://github.com/jbrodriguez/unbalance/issues/50#issuecomment-1073410141
