### ISSUE TITLE
unBALANCE needs exclusive access to disks

### ISSUE THREAD

**Issue by horphi0815** [jbrodriguez/unbalance#51]
Hello,

i installed the unraid plugin and turned off docker and VMs, but unBalance still requesting exclusive access.
i also used already Docker safe new perms to create standard permissions but problem still exist.

Can somebody assist me in this case?

Best regards, Phil

**Comment by jbrodriguez** [comment]
hi, the permission notice is just a warning, but if you're ok with the permissions, you can go on without too much trouble

**Comment by horphi0815** [comment]
But their is still die forbidden sign
![grafik](https://user-images.githubusercontent.com/39962016/162965155-31c7e2ca-bb7b-4e4c-8bb2-3ce5389ec5d7.png)

**Comment by jbrodriguez** [comment]
not sure where that sign comes from, but, have you selected any drives/folders ?

**Comment by horphi0815** [comment]
Yes i selected a drive FROM  and one TO. Also dry run is grey.
No chance to move or copy. 
Can i debug this?

**Comment by horphi0815** [comment]
Ok, dont know why, after restart the server, it works.  i can move now.

Thanks for your support! :-)
