### ISSUE TITLE
Simple way to stand up 'client' for UI enhancement testing?

### ISSUE THREAD

**Issue by cbserra** [jbrodriguez/unbalance#54]
After having to change some of the dependencies locally, I was able to get 'client' to build me a 'dist' folder with what looks to be legitimate content. But, I'm not sure the best way to deploy it. Does it need the server running? I tried to use the Live Server within VS Code but it just brought me to a blank page.

It's basically just a React web app once it's built, correct? Maybe just need to add some scripts to have React deploy it?

**Comment by jbrodriguez** [comment]
hi, yes, if you changed just the frontend, you can deploy (rsync maybe?) the dist folder contents (not dist itself), to `/usr/local/emhttp/plugins/unbalance/app` and it should work

**Comment by cbserra** [comment]
Cool, that's not too bad. But no way to do a local deployment on my laptop? Or on a site like Vercel? I'm guessing some of the scripts are tightly coupled with the unRAID architecture?

And should I not overwrite that folder while Unbalance is processing? I'd imagine it'd be ok since those are only frontend documents but I don't wanna fubar anything.

Thanks!

**Comment by jbrodriguez** [comment]
actually, the frontend talks to a golang backend running on the server, so it's not possible to deploy on vercel or some other host

nothing would really happen if you overwrite the frontend while the app is processing, but it's better to just be safe :)
