### ISSUE TITLE
WebUI is not opening on Unraid 6.12.3

### ISSUE THREAD

**Issue by miodzicho** [jbrodriguez/unbalance#57]
I cannot open WebUI on Unraid 6.12.3, just empty page "This page cannot be reached", tried http and https.
Syslog:
Jul 27 14:25:33 Hydra sudo:     root : PWD=/usr/local/emhttp ; USER=root ; COMMAND=/usr/bin/bash -c '/usr/local/emhttp/plugins/unbalance/unbalance -port 6237'

Config :
root@Hydra:/usr/local/emhttp/plugins/unbalance# cat /boot/config/plugins/unbalance/unbalance.cfg
SERVICE="enable"
PORT="6237"
RUNAS="nobody"

**Comment by jbrodriguez** [comment]
hi, can you make sure you're setting the port in the browser ? http(s)://<server>:6237/

**Comment by miodzicho** [comment]
Seems [Open Web UI ( v5.6.4 )](https://xxxxxxxxx:6238/) is pointing to 6238 not 6237 as configured.

**Comment by dadealus** [comment]
I just recently upgraded from the last 6.11 to 6.12.3.

Unbalance wont complete its startup.  Within the Unraid UI its status stays STOPPED.
I cannot pull up any page on HTTPS://IP:6238  or HTTP://IP:6237


I: 2023/08/15 10:33:02 server.go:151: Server started listening https on :6238
I: 2023/08/15 10:33:02 planner.go:52: starting service Planner ...
F: 2023/08/15 10:33:02 server.go:155: Unable to start on https: tls: failed to find any PEM data in certificate input
I: 2023/08/15 10:33:02 core.go:101: starting service Core ...
I: 2023/08/15 10:33:02 server.go:141: Server started listening http on :6237
I: 2023/08/15 10:34:50 app.go:51: unbalance vv2021.04.21 (5.6.4) starting ...
I: 2023/08/15 10:34:50 app.go:59: No config file specified. Using app defaults ...
I: 2023/08/15 10:34:50 server.go:75: Starting service Server ...
I: 2023/08/15 10:34:50 server.go:92: Serving files from /usr/local/emhttp/plugins/unbalance
I: 2023/08/15 10:34:50 array.go:46: starting service Array ...
I: 2023/08/15 10:34:50 server.go:141: Server started listening http on :6237
I: 2023/08/15 10:34:50 server.go:151: Server started listening https on :6238
F: 2023/08/15 10:34:50 server.go:155: Unable to start on https: tls: failed to find any PEM data in certificate input
I: 2023/08/15 10:34:50 planner.go:52: starting service Planner ...
I: 2023/08/15 10:34:50 core.go:101: starting service Core ...
I: 2023/08/15 10:38:05 app.go:51: unbalance vv2021.04.21 (5.6.4) starting ...
I: 2023/08/15 10:38:05 app.go:59: No config file specified. Using app defaults ...
I: 2023/08/15 10:38:05 server.go:75: Starting service Server ...
I: 2023/08/15 10:38:05 server.go:92: Serving files from /usr/local/emhttp/plugins/unbalance
I: 2023/08/15 10:38:05 array.go:46: starting service Array ...
I: 2023/08/15 10:38:05 server.go:141: Server started listening http on :6237
I: 2023/08/15 10:38:05 server.go:151: Server started listening https on :6238
F: 2023/08/15 10:38:05 server.go:155: Unable to start on https: tls: failed to find any PEM data in certificate input
I: 2023/08/15 10:38:05 planner.go:52: starting service Planner ...
I: 2023/08/15 10:38:05 core.go:101: starting service Core ...

**Comment by xflcx1991** [comment]
Unraid 6.11.5，unBALANCE v5.6.4 
I have the same issue.Start it manually,I got the log:
![图片](https://github.com/jbrodriguez/unbalance/assets/3775351/f37e0132-5d3c-4a0e-9c13-16f4deb09847)

**Comment by jbrodriguez** [comment]
this could be an issue with the ssl certificate, pls report again if this is still an issue
