### ISSUE TITLE
elapsed time counting from "-60" to 0 and then starting back up from "-60"

### ISSUE THREAD

**Issue by 1Euro7Cent** [jbrodriguez/unbalance#59]
Here is an example of the bug

https://github.com/jbrodriguez/unbalance/assets/67194495/e58c3b89-94b8-4357-9f22-f4abf57fa5ff

unBALANCE v2021.04.21 (5.6.4)
Unraid V6.12.5 (I know there is a new version out. I haven’t gotten to it yet)

**Comment by jbrodriguez** [comment]
thanks ! i'll double check that part of the code
