### ISSUE TITLE
Cant stop Unbalanced, Service still running after disabling it. 

### ISSUE THREAD

**Issue by Airfirewall** [jbrodriguez/unbalance#63]
setting "Enable unbalanced server" to "No" Doesn't stop unbalanced, The service is still accessible. I see in unraid logs it tries to run a stop script but guess its not working?
![1](https://github.com/jbrodriguez/unbalance/assets/1653054/680ca351-8c92-478c-9457-13df3f112aaa)
![2](https://github.com/jbrodriguez/unbalance/assets/1653054/af9728ce-4697-4cd0-bdee-7e858e2d67e3)

**Comment by jbrodriguez** [comment]
thanks a lot, i need to update the stop script, will do in the next release !

**Comment by jbrodriguez** [comment]
fixed by #65
