### ISSUE TITLE
version `GLIBC_2.34' not found

### ISSUE THREAD

**Issue by xxzj990** [jbrodriguez/unbalance#64]
Can not start

When i try to start manually with:

```
cd /usr/local/emhttp/plugins/unbalanced
./unbalanced -port 7090
```

get this error:

```
./unbalanced: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./unbalanced)
./unbalanced: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./unbalanced)
```

unraid version: 6.9.1

unbalanced-2024.01.11

my libc info:
`lrwxrwxrwx 1 root root      12 Mar  9  2021 libc.so.6 -> libc-2.30.so*`

**Comment by jbrodriguez** [comment]
hi, that's an old unraid version, i only tested on 6.12.x

it's entirely possible that 6.9.x doesn't contain a recent version of libc :(

btw, the recommended way to run it from the command line would be

```shell
env $(cat /boot/config/plugins/unbalanced/unbalanced.env | xargs) /usr/local/emhttp/plugins/unbalanced --port 7090
```

**Comment by xxzj990** [comment]
> hi, that's an old unraid version, i only tested on 6.12.x
> 
> it's entirely possible that 6.9.x doesn't contain a recent version of libc :(
> 
> btw, the recommended way to run it from the command line would be
> 
> ```shell
> env $(cat /boot/config/plugins/unbalanced/unbalanced.env | xargs) /usr/local/emhttp/plugins/unbalanced --port 7090
> ```

Thanks for your reply, I will continue to use the old version.
