### ISSUE TITLE
Slow down update rate when transferring many folders

### ISSUE THREAD

**Issue by Mikki-10** [jbrodriguez/unbalance#7]
Hi

Im using the plugin to move a lot of folders, so that makes a "big" payload (196kb) for the websocket and then combined with the 250ms pull rate it gives me (779kb/s) 6,2mbit stream for just a status page.

So it could be nice if we can set the update rate for the page, when moving a lot of folders.

(I have 1Gbit LAN and 300/300mbit intrenet, so i do not mind, but for others 6,2mbit might be a lot, when using wifi or VPN in there network to see the status)

**Comment by jbrodriguez** [comment]
Implemented in 5.2.0
