### ISSUE TITLE
Unbalanced is crashing my server

### ISSUE THREAD

**Issue by Deses** [jbrodriguez/unbalance#78]
Hi, I've been trying to use unbalanced to scatter and then gatter files across my array and whenever I use it, it ultimately crashes and reboots the computer.

At first I posted in [the official Unraid forum](https://forums.unraid.net/topic/151902-unraid-server-rebooting-by-itself/), and since the logs show nothing of note they think my computer hardware is faulty, but I don't agree.

The computer has been behaving perfectly with way worse workloads than simple filemoving and with great uptimes, but as soon as I start an unbalanced job it crashes within minutes. It took `3m 33s` last time it crashed.

Now that the rant is over... how could I help you find whats wrong? You can find my previous crash logs on the forum's thread, you might find something else.

Thank you very much for your time.

**Comment by jbrodriguez** [comment]
hi, yes, it's certainly unusual, what unbalanced do is basically run rsync.
a couple of thoughts
- check /var/log/unbalanced.log for additional clues, it has details about the operations being executed
- run unbalanced again but monitor memory with something like htop (maybe the rsync command is generating some memory leak ? 🤷‍♂️)
- run the last rsync command manually and monitor it with htop to

**Comment by Deses** [comment]
Thank you, I'm going to try to run another job and monitor htop.

The unbalanced.log didn't show anything, but let's see if something shows up now.

Also I've run an 8 hour memtest at the suggestion of trurl and there were no errors.
![image](https://github.com/jbrodriguez/unbalance/assets/1654959/c9af5155-208b-4db4-849d-c0a828bc4369)

**Comment by Deses** [comment]
It's been running a gather job for +20 minutes and it didn't crash yet. I hate these "random" bugs. 

Back when I did the scatter job to empty a drive I needed 3 or 4 tries but it ultimately moved everything out of the drive, but I had the corresponding 3 or 4 crashes.

I'll keep monitoring. :)

**Comment by jbrodriguez** [comment]
pls open a new issue if this happens again
