### ISSUE TITLE
Reported rate while moving data is inaccurate

### ISSUE THREAD

**Issue by maor-avni-hpe** [jbrodriguez/unbalance#81]
How is the reported data rate calculated?
I'm currently moving data between disks and see that the reported rate is ~112MB/s, which is much higher than I'd expected.
When I run disk operations like rsync or move I usually get data rates closer to ~60MB/s.
I don't expect unbalance to do any magic, so my only assumption is the reported number is inaccurate, which affects the calculated ETA.

**Comment by jbrodriguez** [comment]
hi, is the reported rate sustained at that speed ?

the current logic calculates speed based on the last 60 samples of your refresh rate setting: if you have 1 sec, it will be the last 60 1sec intervals, if you have 5 secs, the last 60 5secs intervals and so on

transfer rate should reflect more accurately speed variations: speed is lower towards the end of the disk, etc

let me know if it doesn't vary for you

**Comment by jbrodriguez** [comment]
his is how unbalanced reads transferred bytes

https://github.com/jbrodriguez/unbalance/blob/main/daemon/services/core/helper.go#L380

there will always be some overhead against pure rsync calculations

there might a improvement opportunity there, it would require a deeper dive though

**Comment by jbrodriguez** [comment]
that's a fair point, i cannot recall what was my rationale for using rchar vs wchar

i wonder how other monitoring tools do it, although from the linux kernel docs, there doesn't seem to be that much of a difference

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/filesystems/proc.rst?id=HEAD#n1717
![Screenshot 2024-02-13 at 10 50 04](https://github.com/jbrodriguez/unbalance/assets/1305422/6ec9d602-f694-4fd7-8e7e-c8be1fcde431)

that similarity might just not hold true on a real world scenario though 🤷‍♂️

**Comment by maor-avni-hpe** [comment]
Checking into this a little further shows that rchar and wchar are mostly similar. Probably because rsync writes to write cache and is then blocked as the cache is flushed. Or something like that.

But I'm nitpicking here, as eventually copying ~5 TB from disk to disk is going to take several hours.
It's a very useful tool.

**Comment by maor-avni-hpe** [comment]
Short update: Apparently it's related to the target file system. When copying to XFS the reported speed is accurately displayed.
