### ISSUE TITLE
Changing update interval during move displays incorrect throughput rate

### ISSUE THREAD

**Issue by teambvd** [jbrodriguez/unbalance#84]
When a move is in progress, the default interval for display updates is 1s, and this throughput is mostly reliably matched with the IO actually seen on the disk (through CLI or via the unraid UI):
![1s-interval](https://github.com/jbrodriguez/unbalance/assets/70113838/4cdd0e2b-fcd6-4359-8a0b-efbdf9be1cac)

Changing this to another interval such as 5 seconds appears to take the last value it received, and then divides it by the interval number set:
![5s-interval](https://github.com/jbrodriguez/unbalance/assets/70113838/371367a0-d5be-4f89-92ed-10cd14598bb9)

Eventually this catches up, so this is a very small/minor issue, but just figured I'd mention it in case it wasn't something you were already aware of. Appreciate your work on this!

**Comment by jbrodriguez** [comment]
hi,

i think this has to do with the internal samples buffer: it might need to be reset when the interval is changed 

thanks for the report, i'll keep it open for when i work on the app

thanks for the kudos too !
