### ISSUE TITLE
Long running task "resets"

### ISSUE THREAD

**Issue by newhinton** [jbrodriguez/unbalance#92]
Hi! I have been using your tool quite successfully for "smaller" tasks to empty a disk.

However, for longer running tasks (~12h), usually i cannot return to the "planning" ui. After getting the notification that the planning state has been completed, returning to the unbalance-web-ui only shows the default first step, and the former task seems to be gone.

Is there a way to fix this?

Thank you!

**Comment by newhinton** [comment]
Okay, it also sometimes happens to very short tasks.

**Comment by jbrodriguez** [comment]
hi, not really sure, do you seen anything odd in the logs ? 

/var/log/unbalanced.log

**Comment by newhinton** [comment]
This occurs roughly at the time the "planning-finished"-messages comes in:


```
2024/05/04 02:38:51 issues:owner(19852082):group(19852082):folder(2724499):file(17052659)
2024/05/04 03:15:56 items:count(152):size(553.51 GB)
2024/05/04 03:15:56 scanning:disk(/mnt/disk2):folder(Main/Data)
2024/05/04 03:18:10 issues:owner(63449):group(63449):folder(4249):file(59198)
2024/05/04 03:18:10 items:count(4):size(263.99 GB)
2024/05/04 03:18:10 scanning:disk(/mnt/disk2):folder(Main/Data/file.zip)
2024/05/04 03:18:10 issues:not-available:(exit status 1)
2024/05/04 03:18:10 items:count(1):size(111.10 KB)
```

Then there are a lot of `scatterPlan:found`-entries, and `scatterPlan:willBeTransferred`

Sometimes there is a:
`2024/05/04 03:51:06 unable to read websocket message: websocket: close 1001 (going away): Child was killed`-message. Does the websocket need to stay alive for this?

**Comment by jbrodriguez** [comment]
> 2024/05/04 03:18:10 issues:not-available:(exit status 1)
that log line is not so good, may point to an issue with the underlying file/folder



> `2024/05/04 03:51:06 unable to read websocket message: websocket: close 1001 (going away): Child was killed`-message. Does the websocket need to stay alive for this?

these are "safe", it's the server logging the fact that the browser disconnected

**Comment by jbrodriguez** [comment]
pls open a new issue if this happens again
