### ISSUE TITLE
unable to read websocket message: websocket: close 1006 (abnormal closure): unexpected EOF

### ISSUE THREAD

**Issue by g-vdn** [jbrodriguez/unbalance#96]
Placed unbalanced behind Nginx Proxy Manager and enabled websocket support, no other config added to nginx. 
I can access the app , browse the options, but when it has to do calculations, just gets stuck and in logs I see:

unable to read websocket message: websocket: close 1006 (abnormal closure): unexpected EOF

Is there a nginx config I should use to be able to access unbalanced through NPM, or just I just stick to localhost:7090 ?

**Comment by jbrodriguez** [comment]
i haven't tried running unbalanced behind a reverse proxy, but it should kinda work :)

the websocket close message is generic, when you close the browser it logs that

i have wireguard running, so i just treat any service inside as if i were inside my lan

**Comment by g-vdn** [comment]
I encountered this issue locally, below is my set-up:

- PiHole DNS which has mydomain.com pointing to 10.0.0.1 (unraid server)
- CNAME for unbalanced.mydomain.com pointing to mydomain.com
- NGINX entry which has unbalanced.mydomain.com proxying to unraid_hostname:7090

I used GATHER, selected few shares and clicked next. Some shares contain thousands of files (nextcloud , immich share, with many thumbnails), perhaps I have hit some timeout on nginx side, using localhost:7090 worked like a charm

Will try to see if I can find something on nginx config side.

Thank for replying, and amazing job on the app, love it
